############### File Inputs ######################
# These inputs monitor local Claude Desktop log files on Windows.
# Claude Desktop Default Path: $APPDATA=C:\Users\<User>\AppData\Roaming\Claude
##################################################

[monitor://C:\Users\*\AppData\Roaming\Claude\logs\main.log]
disabled = 1
sourcetype = claude:desktop:main

[monitor://C:\Users\*\AppData\Roaming\Claude\logs\mcp*.log]
disabled = 1
sourcetype = claude:desktop:mcp

[monitor://C:\Users\*\AppData\Roaming\Claude\logs\coworkd.log]
disabled = 1
sourcetype = claude:desktop:cowork

[monitor://C:\Users\*\AppData\Roaming\Claude\logs\cowork_vm_*.log]
disabled = 1
sourcetype = claude:desktop:cowork

[monitor://C:\Users\*\AppData\Roaming\Claude\logs\claude.ai-web.log]
disabled = 1
sourcetype = claude:desktop:web

[monitor://C:\Users\*\AppData\Roaming\Claude\logs\ssh.log]
disabled = 1
sourcetype = claude:desktop:main

[monitor://C:\Users\*\AppData\Roaming\Claude\logs\unknown-window.log]
disabled = 1
sourcetype = claude:desktop:main


############### Claude Config ##################
# These inputs monitor Claude Desktop config files.
# Claude Desktop Default Path: $APPDATA=C:\Users\<User>\AppData\Roaming\Claude
################################################

[monitor://C:\Users\*\AppData\Roaming\Claude\claude_desktop_config.json]
disabled = 1
sourcetype = _json

[monitor://C:\Users\*\AppData\Roaming\Claude\config.json]
disabled = 1
sourcetype = _json

[monitor://C:\Users\*\AppData\Roaming\Claude\cowork-enabled-cli-ops.json]
disabled = 1
sourcetype = _json

[monitor://C:\Users\*\AppData\Roaming\Claude\extensions-blocklist.json]
disabled = 1
sourcetype = _json

[monitor://C:\Users\*\AppData\Roaming\Claude\git-worktrees.json]
disabled = 1
sourcetype = _json

[monitor://C:\Users\*\AppData\Roaming\Claude\window-state.json]
disabled = 1
sourcetype = _json

[monitor://C:\Users\*\AppData\Roaming\Claude\plan-usage-history.json]
disabled = 1
sourcetype = _json
