######################### Windows File Inputs #################################
# These inputs monitor local Claude Desktop log files on Windows.
# Claude Desktop Default Path: $APPDATA\Claude ($APPDATA=C:\Users\<User>\AppData\Roaming)
#    The case of MSIX Install: $LOCALAPPDATA\Packages\Claude_<hash>\LocalCache\Roaming\Claude ($LOCALAPPDATA=C:\Users\<user>\AppData\Local\)
# Please see https://github.com/anthropics/claude-code/issues/25579
# Claude Desktop for 3rd party Path: $LOCALAPPDATA\Claude-3p ($LOCALAPPDATA=C:\Users\<User>\AppData\Local\)
# Please see https://claude.com/docs/third-party/claude-desktop/data-storage#where-data-lives
###############################################################################

[monitor://C:\Users\*\AppData\Roaming\Claude\logs\main.log]
disabled = 1
sourcetype = claude:desktop:main

[monitor://C:\Users\*\AppData\Roaming\Claude\logs\mcp*.log]
disabled = 1
sourcetype = claude:desktop:mcp

[monitor://C:\Users\*\AppData\Roaming\Claude\logs\coworkd.log]
disabled = 1
sourcetype = claude:desktop:cowork

[monitor://C:\Users\*\AppData\Roaming\Claude\logs\cowork_vm_*.log]
disabled = 1
sourcetype = claude:desktop:cowork

[monitor://C:\Users\*\AppData\Roaming\Claude\logs\cowork-service.log]
disabled = 1
sourcetype = claude:desktop:cowork:service

[monitor://C:\Users\*\AppData\Roaming\Claude\logs\claude.ai-web.log]
disabled = 1
sourcetype = claude:desktop:web

[monitor://C:\Users\*\AppData\Roaming\Claude\logs\ssh.log]
disabled = 1
sourcetype = claude:desktop:main

[monitor://C:\Users\*\AppData\Roaming\Claude\logs\unknown-window.log]
disabled = 1
sourcetype = claude:desktop:main



######################### Mac File Inputs #################################
# These inputs monitor local Claude Desktop log files on Mac.
# Claude Desktop Default Path: /Users/<User>/Library/Logs/Claude
# Claude Desktop for 3rd party Path: /Users/<User>/Library/Logs/Claude-3p/
###############################################################################

[monitor:///Users/*/Library/Logs/Claude/main.log]
disabled = 1
sourcetype = claude:desktop:main

[monitor:///Users/*/Library/Logs/Claude/mcp*.log]
disabled = 1
sourcetype = claude:desktop:mcp

[monitor:///Users/*/Library/Logs/Claude/coworkd.log]
disabled = 1
sourcetype = claude:desktop:cowork

[monitor:///Users/*/Library/Logs/Claude/cowork_vm_*.log]
disabled = 1
sourcetype = claude:desktop:cowork

[monitor:///Users/*/Library/Logs/Claude/cowork-service.log]
disabled = 1
sourcetype = claude:desktop:cowork:service

[monitor:///Users/*/Library/Logs/Claude/claude.ai-web.log]
disabled = 1
sourcetype = claude:desktop:web

[monitor:///Users/*/Library/Logs/Claude/ssh.log]
disabled = 1
sourcetype = claude:desktop:main

[monitor:///Users/*/Library/Logs/Claude/unknown-window.log]
disabled = 1
sourcetype = claude:desktop:main
