[claude_index]
definition = index=*
iseval = 0
description = Defines the index searched for Claude Desktop logs. Override specified Indexes if you route these logs to a different index.

[claude_sourcetype_main]
definition = sourcetype=claude:desktop:main
iseval = 0
description = Main Claude Desktop log sourcetypes.

[claude_sourcetype_mcp]
definition = sourcetype=claude:desktop:mcp
iseval = 0
description = MCP log sourcetypes.

[claude_sourcetype_web]
definition = sourcetype=claude:desktop:web
iseval = 0
description = Web-layer log sourcetypes.

[claude_sourcetype_cowork]
definition = sourcetype=claude:desktop:cowork
iseval = 0
description = Cowork sandbox VM log sourcetypes.
